openapi: "3.0.1"
info:
  title: sample title(change me!)
  version: 1.0.0
  description: Lorem ipsum dolor sit amet.(Change me!)
servers:
  - url: "localhost:13500"
    description: 手元の環境
paths:
  '/v1/check':
    get:
      tags:
        - v1
      operationId: root
      responses:
        '200':
          description: Pointの取得成功
          content:
            application/json:
              schema:
                type: object
                example:
                  message: "Hello world"
        '400':
          description: 不正なリクエストです。
        '401':
          description: 認証エラーです。
  '/v1/health_check':
    get:
      tags:
        - v1
      operationId: health_check
      responses:
        '200':
          description: システムは正常
          content:
            application/json:
              schema:
                type: object
                example:
                  message: "System All Green!"
        '400':
          description: 不正なリクエストです。
        '401':
          description: 認証エラーです。
  '/v1/double':
    get:
      tags:
        - v1
      operationId: double
      parameters:
        - $ref: '#/components/parameters/num_input'
      responses:
        '200':
          descripion: 入力した値の二乗を返す
          content:
            application/json:
              schema:
                type: object
                example:
                  message: "4"
        '400':
          descripion: 不正なリクエスト
tags:
  - name: v1
    description: Version 1 endpoints
components:
  parameters:
    num_input:
      name: num_input
      in: query
      descripion: This is sample num_input
      required: true
      schema:
        type: integer
  schemas:
    Sample:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: sample_name
        url:
          type: string
          example: 'https://www.example.com'
    PokemonCards:
      type: array
      items:
        $ref: '#/components/schemas/PokemonCard'
      properties:
        id:
          type: integer
          format: int64
          example: 4
    PokemonCard:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 4
        expansion:
          type: string
          example: SV2D
        collection:
          type: string
          example: 075/071
        rare:
          type: string
          example: AR
        type:
          type: string
          example: ポケモン
        subtype:
          example: 超
          type: string
        name:
          type: string
          example: スナバァ
        author:
          type: string
          example: Teeziro
        img_url:
          type: string
          example: "https://www.pokemon-card.com/assets/images/card_images/large/SV2D/043643_P_SUNABAA.jpg"
        created_at:
          type: string
          format: date-time
          example: 2023-11-10 13:54:13
