/*
 * sample title(change me!)
 *
 * Lorem ipsum dolor sit amet.(Change me!)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
)

type V1API struct {
	// Get /v1/double
	// 
	Double gin.HandlerFunc
	// Get /v1/health_check
	// 
	HealthCheck gin.HandlerFunc
	// Get /v1/check
	// 
	Root gin.HandlerFunc
}
