/*
 * sample title(change me!)
 *
 * Lorem ipsum dolor sit amet.(Change me!)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Sample struct {

	Id int64 `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	Url string `json:"url,omitempty"`
}
