/*
 * sample title(change me!)
 *
 * Lorem ipsum dolor sit amet.(Change me!)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PokemonCards struct {
}
