/*
 * sample title(change me!)
 *
 * Lorem ipsum dolor sit amet.(Change me!)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type PokemonCard struct {

	Id int64 `json:"id,omitempty"`

	Expansion string `json:"expansion,omitempty"`

	Collection string `json:"collection,omitempty"`

	Rare string `json:"rare,omitempty"`

	Type string `json:"type,omitempty"`

	Subtype string `json:"subtype,omitempty"`

	Name string `json:"name,omitempty"`

	Author string `json:"author,omitempty"`

	ImgUrl string `json:"img_url,omitempty"`

	CreatedAt time.Time `json:"created_at,omitempty"`
}
