openapi: 3.0.1
info:
  description: Lorem ipsum dolor sit amet.(Change me!)
  title: sample title(change me!)
  version: 1.0.0
servers:
- description: 手元の環境
  url: localhost:13500
tags:
- description: Version 1 endpoints
  name: v1
paths:
  /v1/check:
    get:
      operationId: root
      responses:
        "200":
          content:
            application/json:
              schema:
                example:
                  message: Hello world
                type: object
          description: Pointの取得成功
        "400":
          description: 不正なリクエストです。
        "401":
          description: 認証エラーです。
      tags:
      - v1
  /v1/health_check:
    get:
      operationId: health_check
      responses:
        "200":
          content:
            application/json:
              schema:
                example:
                  message: System All Green!
                type: object
          description: システムは正常
        "400":
          description: 不正なリクエストです。
        "401":
          description: 認証エラーです。
      tags:
      - v1
  /v1/double:
    get:
      operationId: double
      parameters:
      - description: This is sample num_input
        explode: true
        in: query
        name: num_input
        required: true
        schema:
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                example:
                  message: "4"
                type: object
          description: 入力した値の二乗を返す
        "400":
          description: 不正なリクエスト
      tags:
      - v1
components:
  parameters:
    num_input:
      description: This is sample num_input
      explode: true
      in: query
      name: num_input
      required: true
      schema:
        type: integer
      style: form
  schemas:
    Sample:
      properties:
        id:
          example: 1
          format: int64
          type: integer
        name:
          example: sample_name
          type: string
        url:
          example: https://www.example.com
          type: string
      type: object
    PokemonCards:
      items:
        $ref: '#/components/schemas/PokemonCard'
      properties:
        id:
          example: 4
          format: int64
          type: integer
      type: array
    PokemonCard:
      properties:
        id:
          example: 4
          format: int64
          type: integer
        expansion:
          example: SV2D
          type: string
        collection:
          example: 075/071
          type: string
        rare:
          example: AR
          type: string
        type:
          example: ポケモン
          type: string
        subtype:
          example: 超
          type: string
        name:
          example: スナバァ
          type: string
        author:
          example: Teeziro
          type: string
        img_url:
          example: https://www.pokemon-card.com/assets/images/card_images/large/SV2D/043643_P_SUNABAA.jpg
          type: string
        created_at:
          format: date-time
          type: string
      type: object
